# Plugins
plugin:
  sendkey:
    keypress_delay: 10

swipe:
  3:
    pinch_in:
      command: "xdotool keydown ctrl click 5 keyup ctrl"
    pinch_out:
      command: "xdotool keydown ctrl click 4 keyup ctrl"

pinch:
  in:
    threshold: 0.05
    command: >
      xdotool keydown ctrl &&
      xdotool click --repeat 3 --delay 5 5 &&
      xdotool keyup ctrl
  out:
    threshold: 0.05
    command: >
      xdotool keydown ctrl &&
      xdotool click --repeat 3 --delay 5 4 &&
      xdotool keyup ctrl


interval:
  pinch: 0.3
